### ISSUE TITLE
Convolution expects input with rank 4, got 5

### ISSUE THREAD

**Issue by hungryquiter** [astorfi/3D-convolutional-speaker-recognition#39]
Traceback (most recent call last):
  File "./code/1-development/train_softmax.py", line 602, in <module>
    tf.app.run()
  File "/opt/tensorflow/python2.7/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "./code/1-development/train_softmax.py", line 414, in main
    logits, end_points_speech = model_speech_fn(batch_speech[i * step: (i + 1) * step])
  File "/opt/speaker-recognition/code/1-development/nets/nets_factory.py", line 59, in network_fn
    return func(images, num_classes, is_training=is_training)
  File "/opt/speaker-recognition/code/1-development/nets/cnn_speech.py", line 118, in speech_cnn
    net = slim.conv2d(inputs, 16, [3, 1, 5], stride=[1, 1, 1], scope='conv11')
  File "/opt/tensorflow/python2.7/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/opt/tensorflow/python2.7/local/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1154, in convolution2d
    conv_dims=2)
  File "/opt/tensorflow/python2.7/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/opt/tensorflow/python2.7/local/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1025, in convolution
    (conv_dims + 2, input_rank))
ValueError: Convolution expects input with rank 4, got 5

**Comment by hungryquiter** [comment]
which version of tensorflow

**Comment by imranparuk** [comment]
related to [issue 38](https://github.com/astorfi/3D-convolutional-speaker-recognition/issues/38) maybe?

**Comment by astorfi** [comment]
@imranparuk Yes. Thanks for pointing it out.

**Comment by astorfi** [comment]
It's a versioning problem.

**Comment by dzfowen** [comment]
speech = tf.placeholder(tf.float32, (20, 80, 40, 1))  
if I deleted the last 1, is it suitable for all versions of TF?
thanks

**Comment by dzfowen** [comment]
sorry the latest version of tf has provided slim.conv3d, it works

**Comment by dzfowen** [comment]
hi  another question: problem about 
# Squeeze spatially to eliminate extra dimensions.(embedding layer)
            if spatial_squeeze:
                logits = tf.squeeze(logits, [1, 2, 3], name='fc/squeezed')

a error happened ,  could I USE logits = tf.squeeze(logits, name='fc/squeezed') instead?

**Comment by imranparuk** [comment]
Hi @dzfowen , the code works out the box, you do not need to change anything. Your issue is that you have the incorrect version of numpy+tensorflow. This will be eventually sorted out i'm sure but for now what you need to do is use a virtual environment, uninstall numpy, install tensorflow version 1 which ships with its own numpy. This should fix your issues.

**Comment by imranparuk** [comment]
```
      spatial_squeeze: whether or not should squeeze the spatial dimensions of the
        outputs. Useful to remove unnecessary dimensions for classification.
```
@dzfowen, no problem. I think it is possible to get the implementation working without the spatial squeeze, it seems to just be there to speed up training (The author should comment its use in more depth). However if python is complaining about dimensions with regard to the squeeze or any other portions of the model it is a good indication that your source of error is due to the mismatch in tensorflow and numpy versions.

**Comment by luoqingshan** [comment]
Convolution expects input with rank 4, got 2
