### ISSUE TITLE
Run time error in the demo

### ISSUE THREAD

**Issue by sivagururaman** [astorfi/3D-convolutional-speaker-recognition#42]
When I ran the run.sh, the execution terminated saying:
FileNotFoundError: [Errno 2] No such file or directory: 'results/SCORES/score_vector.npy'

Where do i get this score file from? Do I need to create one? I just ran the run.sh for demo.

Can you please help?

Regards!

**Comment by sivagururaman** [comment]
Further looking into the code, looks like the demo broke while trying to execute the tf.app.run() especially in the conv stage. The rank of the matrix being different from what is expected. 

COnsole error is as below:
-------
Traceback (most recent call last):
  File "./code/1-development/train_softmax.py", line 602, in <module>
    tf.app.run()
  File "/home/osboxes/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "./code/1-development/train_softmax.py", line 414, in main
    logits, end_points_speech = model_speech_fn(batch_speech[i * step: (i + 1) * step])
  File "/home/osboxes/3D_CNN/3D-convolutional-speaker-recognition/code/1-development/nets/nets_factory.py", line 59, in network_fn
    return func(images, num_classes, is_training=is_training)
  File "/home/osboxes/3D_CNN/3D-convolutional-speaker-recognition/code/1-development/nets/cnn_speech.py", line 118, in speech_cnn
    net = slim.conv2d(inputs, 16, [3, 1, 5], stride=[1, 1, 1], scope='conv11')
  File "/home/osboxes/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/home/osboxes/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1154, in convolution2d
    conv_dims=2)
  File "/home/osboxes/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 183, in func_with_args
    return func(*args, **current_args)
  File "/home/osboxes/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1025, in convolution
    (conv_dims + 2, input_rank))
ValueError: Convolution expects input with rank 4, got 5
------------

**Comment by sivagururaman** [comment]
I think there is another thread on the same topic and seems to mention to use older Tensorflow. Is that correct? Do i need to revert to v1.0.0?

**Comment by sivagururaman** [comment]
With tensorflow v1.0.0 i was able to get past the training. But enrollment is not going through:
Traceback (most recent call last):
  File "./code/2-enrollment/enrollment.py", line 330, in <module>
    tf.app.run()
  File "/home/osboxes/anaconda3/envs/py36/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "./code/2-enrollment/enrollment.py", line 201, in main
    for i in xrange(FLAGS.num_clones):
NameError: name 'xrange' is not defined

**Comment by astorfi** [comment]
Please update your fork.

**Comment by ooobsidian** [comment]
@sivagururaman Have you solved your problem？
